server:
  port: 88

spring:
  application:
    name: yunmall-gateway
  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        # 商品服务的路由规则
        - id: product_route
          uri: lb://yunmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # 第三方服务的路由规则
        - id: third-party-route
          uri: lb://yunmall-third-party
          predicates:
            - Path=/api/third-party/**
          filters:
            - RewritePath=/api/third-party/(?<segment>.*), /$\{segment}
        # 会员服务的路由规则
        - id: member-route
          uri: lb://yunmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # 库存服务的路由规则
        - id: ware-route
          uri: lb://yunmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # 会员服务的路由规则
        - id: coupon-route
          uri: lb://yunmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # 后台管理系统的路由规则
        - id: admin_route
          uri: lb://renren-fast # 负载均衡到 renren-fast
          predicates:
            - Path=/api/**   # 前端的请求都带 /api 前缀
          filters:
            # 前端发来的请求 /api/... 被重写成 /renren-fast/...
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
        # Nginx 路由到网关，注意需要放在最后面，因为路由规则是匹配域名，一旦匹配到了域名，就全会匹配当前路由规则
        # 导致无法再匹配其他路由规则。即host规则要放在path规则后，host更加粗粒度
        - id: yunmall-host-route
          uri: lb://yunmall-product
          predicates:
            - Host=**.yuyunzhao.cn



## 前端项目发来的请求都带有 /api 前缀。转发到路由服务后，需要重写路径，将 /api 前缀给去掉
## 注意，要将精确的路径放在更前面，代表优先级更高
# http://localhost:88/api/catcha.jpg?uuid=xxxx   ->  http://localhost:8080/renren-fast/catcha.jpg?uuid=xxxx
# http://localhost:88/api/product/category/list/tree -> http://localhost:10000/product/category/list/tree


