server:
  port: 88

spring:
  application:
    name: yunmall-gateway
  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq


