
spring:
  # 数据源
  datasource:
    username: root
    password: zhaoyuyun
    url: jdbc:mysql://47.98.120.35:3306/yunmall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    # 注意驱动类名，5.0版本和8.0版本不同
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Spring Cloud
  cloud:
    nacos:
      # 服务注册中心
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      # 设置主键自增
      id-type: auto
