server:
  port: 10000

spring:
  datasource:
    username: root
    password: zhaoyuyun
    url: jdbc:mysql://47.98.120.35:3306/yunmall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: yuyunzhao.cn
    port: 6379
    password: zhaoyuyun # 设置密码防止被别人利用


  cloud:
    # 服务注册中心
    nacos:
      discovery:
        server-addr: localhost:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false   # 开发期间关闭缓存
  resources:
    static-locations: [classpath:/static/]
  mvc:
    static-path-pattern: /static/**  # 因为所有的请求都额外带了前缀 /static/，为了后期动静分离


mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      # 设置主键自增
      id-type: auto
      # 设置逻辑删除
      logic-delete-value: 1     # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 开启日志
logging:
  level:
    com.zhao.yunmall: error  # 服务上线后，设置为 error




