server:
  port: 12000

spring:
  application:
    name: yunmall-search
  cloud:
    nacos:
      # 服务注册中心
      discovery:
        server-addr: localhost:8848
  resources:
    static-locations: [ classpath:/static/ ]
  mvc:
    static-path-pattern: /static/**  # 因为所有的请求都额外带了前缀 /static/，为了后期动静分离
  thymeleaf:
    cache: false

