server:
  port: 30000

spring:
  cloud:
    nacos:
      # 服务注册中心
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI5tPg8hhbq8wNcjPS9uiv
      secret-key: Bylo34G1xcs3cnQejXC4tpuJ0Ybrkw
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: yunmall-project
