server:
  port: 30000

spring:
  cloud:
    nacos:
      # 服务注册中心
      discovery:
        server-addr: localhost:8848
    alicloud:
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        appcode: 37023c3c23914719a9685a97a492a180
